version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile.full
    container_name: sast_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./reports:/app/reports
      - /var/run/docker.sock:/var/run/docker.sock
      - /c:/mnt/c
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped
